POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "title": "react for rookies",
    "author": "fullStackOpen",
    "url": "fullstackopen.com/part4",
    "likes": 51000,
    "user": "67d88ea7c0f0380a6fda56ec"
}

###
GET http://localhost:3000/api/blogs