GET http://localhost:3000/api/blogs

###
POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJydW5vODgiLCJpZCI6IjY3ZDg1NDAwZWJlMzcxM2JhZjkyMjUzNSIsImlhdCI6MTc0MjMxMzU3Mn0.mvOOzNHl9hoDwZLcKVKPMlrn02FzBNs95n2wmMuEel8
{
    "title": "Testing from Rest Client",
    "author": "VS Code",
    "url": "restclient.com",
    "likes": 12345
}
