POST  http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name" : "Jose",
    "number": "000"
}

###

GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/67c7ba5e77d9bd647386bfcc

###
DELETE http://localhost:3001/api/persons/67c84a3bb7a0314292d23095

###
PUT http://localhost:3001/api/persons/67c99db8e625964292e23178
Content-Type: application/json

{
  "name": "Bruno",
  "number": "987654"
}


//3.10
###
GET https://render-part3-m603.onrender.com/api/persons